package Produtos;
import Produtos.DadosProdutos;

import agendatelefonica.MyPostgreSQL;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

public class  TelaCadastroProduto extends javax.swing.JFrame
{
 private MyPostgreSQL pgBD; // conexão com banco de dados
 private ArrayList<Produto> listaProdutos;

 public TelaCadastroProduto()
 {
 initComponents();
 setDefaultCloseOperation(HIDE_ON_CLOSE); //usar esse código para fechar esse JFRAME e não a tela principal


 // adiciona change listener no campo de texto:
 // o método filtroAlterou() será chamado toda vez que o
 // conteúdo de filtroTextField for alterado.
 filtroTextField.getDocument().addDocumentListener(new DocumentListener() {
 @Override
 public void insertUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 @Override
 public void removeUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 @Override
 public void changedUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 });

 // conecta com base de dados
 pgBD = new MyPostgreSQL();
 pgBD.conecta();

 // recupera dados da base de dados
 listaProdutos = DadosProdutos.lerDados(pgBD.getConnection());
 mostraDados(listaProdutos);

 // centralizar a janela na tela
 this.setLocationRelativeTo(null);
 }
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        filtroTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        novoProdutoMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos Cadastrados");
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        filtroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas Cadastradas"));

        produtosTable.setAutoCreateRowSorter(true);
        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EAN", "Produto", "Descrição", "Quantidade", "Valor", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtosTable.getTableHeader().setReorderingAllowed(false);
        produtosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(produtosTable);
        if (produtosTable.getColumnModel().getColumnCount() > 0) {
            produtosTable.getColumnModel().getColumn(0).setMinWidth(1);
            produtosTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            produtosTable.getColumnModel().getColumn(0).setMaxWidth(1);
            produtosTable.getColumnModel().getColumn(1).setMinWidth(100);
            produtosTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            produtosTable.getColumnModel().getColumn(1).setMaxWidth(100);
            produtosTable.getColumnModel().getColumn(4).setMinWidth(20);
            produtosTable.getColumnModel().getColumn(4).setMaxWidth(80);
            produtosTable.getColumnModel().getColumn(5).setMinWidth(20);
            produtosTable.getColumnModel().getColumn(5).setPreferredWidth(80);
            produtosTable.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Produtos");

        novoProdutoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        novoProdutoMenuItem.setText("Novo Produto");
        novoProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProdutoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(novoProdutoMenuItem);

        sairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_novoProdutoMenuItemActionPerformed
    {//GEN-HEADEREND:event_novoProdutoMenuItemActionPerformed
// ativa janela para editar dados da pessoa selecionada
 TelaInserirProduto pDialog = new TelaInserirProduto(this, true);
 pDialog.setConnection(pgBD.getConnection());
 pDialog.setTitle("Cadastro novo produto");
 pDialog.inserindoNovo(true);
 pDialog.setVisible(true);
 if(pDialog.getOperacao() == TelaCadastroProduto.OPERACAO_OK)
 {
 // obtém dados informados pelo usuário
 Produto p = pDialog.getProduto();
 Produto novo = new Produto(p.getId(),  p.getEAN13(), p.getNomeProduto(), p.getDescricaoProduto(), p.getQtdEstoque(),
                                        p.getPrecoProduto(), p.getUnidMedida()); 
 
 // insere dados na lista de pessoas e ordena
 listaProdutos.add(novo);
 // atualiza dados na tabela
 filtroTextField.setText(""); // para garantir que todos os dados serão mostrados
 mostraDados(listaProdutos);
 }    }//GEN-LAST:event_novoProdutoMenuItemActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sairMenuItemActionPerformed
    {//GEN-HEADEREND:event_sairMenuItemActionPerformed

   // System.exit(0);
        
        TelaCadastroProduto form = new TelaCadastroProduto();
        
        this.dispose();

    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void produtosTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_produtosTableMouseClicked
    {//GEN-HEADEREND:event_produtosTableMouseClicked
     // double-click: editar dados da pessoa
 if (evt.getClickCount() >= 2)
 {
 /*
 * IMPORTANTE: quando uma tabela usa um ordenador, os dados que o usuário
 * vê podem estar em uma ordem diferente da que está especificada no modelo
 * interno (data model). Os dados que o usuário vê é conhecido como uma view,
 * e possui seu próprio conjunto de coordenadas. Portanto, é necessário
 * converter as coordenadas do modelo para as coordenadas da view.
 *
 * Quando usar um ordenador, SEMPRE converta as coordenadas das células
 */
 int rowModel = produtosTable.getSelectedRow(); // coordenadas do modelo
 // coordenadas da view
 int rowView = produtosTable.convertRowIndexToModel(rowModel);

 // obtem dados da pessoa selecionada
 DefaultTableModel model = (DefaultTableModel) produtosTable.getModel();
 ArrayList<Produto> lista = 
 buscaNomesTelefones((String)model.getValueAt(rowView, 2));
 if((lista == null) || lista.isEmpty())
 return;

 Produto selecionado = lista.get(0);

 // ativa janela para editar dados da pessoa selecionada
 TelaInserirProduto pDialog = new TelaInserirProduto(this, true);
 pDialog.setConnection(pgBD.getConnection());
 pDialog.setTitle("Manutenção dados");
 pDialog.setProduto(selecionado);
 pDialog.inserindoNovo(false);
 pDialog.setVisible(true);
 switch(pDialog.getOperacao())
 {
 case TelaInserirProduto.OPERACAO_OK:
 // obtém dados informados pelo usuário
 Produto p = pDialog.getProduto();

 
 
 selecionado.setId(p.getId());
 
 // atualiza telefone (nome não pode ser alterado)
 //selecionado.setFone(p.getFone());
 // atualiza dados na tabela
 //model.setValueAt(p.getFoneFormatado(), rowView, 1);
 
 //selecionada.setFone_Comercial(p.getFone_Comercial_Formatado());
 // atualiza dados na tabela
 //selecionado.setFone_Comercial(p.getFone_Comercial());
// model.setValueAt(p.getFone_Comercial(), rowView, 2);
 
 //selecionado.setFone_Residencial(p.getFone_Residencial());
 //model.setValueAt(p.getFone_Residencial(), rowView, 3);
 
// selecionado.setCPF(p.getCPF());
// model.setValueAt(p.getCPF(), rowView, 4);
 
 //selecionado.setRG(p.getRG());
 //model.setValueAt(p.getRG(), rowView, 5);
 
 
 break;
 case TelaInserirProduto.OPERACAO_ELIMINAR:
 // elimina pessoa da lista de pessoas
 listaProdutos.remove(selecionado);

 // atualiza dados na tabela
 model.removeRow(rowView);
 break;
 }
 }
    }//GEN-LAST:event_produtosTableMouseClicked

    private void filtroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTextFieldActionPerformed
    
    public ArrayList<Produto> buscaNomesTelefones(String procurado)
    {
        if((procurado == null) || procurado.isEmpty())
 return listaProdutos;

 ArrayList<Produto> produtosEncontrados = new ArrayList<>();
 String minusculo = procurado.toLowerCase();
 boolean achou = false;

 // percorrer toda a lista de pessoas
 for(Produto p : listaProdutos)
 {
 // verifica se dado procurado aparece no nome ou telefone
 if(p.getNomeProduto().toLowerCase().contains(minusculo) ||
 p.getEAN13().contains(procurado)//||
 //p.getFone_Comercial().contains(procurado)
         )
 {
 achou = true;
 produtosEncontrados.add(p);
 }
 }

 if(achou)
 return produtosEncontrados;
 else
 return null;
    }
    
    private void filtroAlterou()
    {
  ArrayList<Produto> filtro = buscaNomesTelefones(filtroTextField.getText());
 mostraDados(filtro);

    }
    
    
    
    private void mostraDados(ArrayList<Produto> dados)
    {
       try
 {
 // limpa dados da tabela
 DefaultTableModel model = (DefaultTableModel) produtosTable.getModel();
 model.setRowCount(0);

 if((dados == null) || (dados.isEmpty()))
 return;

 // percorrer lista de pessoas e mostrar dados
 for (Produto p : dados)
 {                                                                          //=-=-=-=-=-=-=-=-=-//=-=-=-=-=-=-=-=-=-
 model.addRow(new Object[]{p.getId(), p.getEAN13(), p.getNomeProduto(),  p.getDescricaoProduto(), 
                           p.getQtdEstoque(), p.getPrecoProduto(),  p.getUnidMedida()});
            
// add os 3 campos em pessoa , que é add na lista, que depois joga na tabela da tela gráfica
                                                                        
 }
 }
 catch(Exception ex)
 {
 JOptionPane.showMessageDialog(this,
"Erro ao atualizar tabela\n" + ex.getMessage(),
 "Mostrar dados", JOptionPane.ERROR_MESSAGE);
 }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelaCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filtroTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem novoProdutoMenuItem;
    private javax.swing.JTable produtosTable;
    private javax.swing.JMenuItem sairMenuItem;
    // End of variables declaration//GEN-END:variables
}
