package Produtos;
import Produtos.Produto;
import Produtos.TelaCadastroProduto;
import Produtos.DadosProdutos;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class TelaInserirProduto extends javax.swing.JDialog
{
 // operacao feita pelo usuario
 public static final int OPERACAO_OK = 0;
 public static final int OPERACAO_ELIMINAR = 1;
 public static final int OPERACAO_CANCELAR = 2;
 
 private Connection bdConnection;
 private Produto pCurrent2; // dados da pessoa corrente
 private int operacao;
 private boolean estaInserindo;
 private final TelaCadastroProduto janelaPai2;

 public TelaInserirProduto(java.awt.Frame parent, boolean modal)
 {
 super(parent, modal);
 initComponents();

 pCurrent2 = new Produto();
 estaInserindo = true;
 janelaPai2 = (TelaCadastroProduto)parent;

 bdConnection = null;

 // centraliza janela na tela
 this.setLocationRelativeTo(null);
 }

 public void setConnection(Connection bdConnection)
 {
 this.bdConnection = bdConnection;
 }

 public int getOperacao()
 {
 return operacao;
 }

 public Produto getProduto()
 {
 return pCurrent2;
 }

 public void setProduto(Produto p)
 {
 if(p != null)
 {
 pCurrent2 = new Produto(p.getId(), p.getEAN13(), p.getNomeProduto(),  p.getDescricaoProduto(), p.getQtdEstoque(),
                         p.getPrecoProduto(), p.getUnidMedida());
 
 EAN13TextField.setText(p.getEAN13());
 nomeProdutoTextField.setText(p.getNomeProduto());
 DescricaoProdutoTextField.setText(p.getDescricaoProduto());
 QtdEstoqueTextField.setText(p.getQTDEstoque());
 ValorProdutoTextField.setText(p.getPrecoProduto());
 UnidMedidaProdutoTextField.setText(p.getUnidMedida());
 

 }
 }

 public void inserindoNovo(boolean novoProduto)
 {
 estaInserindo = novoProduto;

 if (novoProduto)
 {
 eliminaButton.setEnabled(false);
 }
 else
 {
 nomeProdutoTextField.setEditable(false);
 nomeProdutoTextField.setFocusable(false);
 eliminaButton.setEnabled(true);
 }
 }
 
 
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeProdutoTextField = new javax.swing.JTextField();
        ValorProdutoTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        eliminaButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EAN13TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DescricaoProdutoTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UnidMedidaProdutoTextField = new javax.swing.JTextField();
        QtdEstoqueTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produto:");

        jLabel2.setText("Valor:");

        nomeProdutoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoTextFieldActionPerformed(evt);
            }
        });

        ValorProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorProdutoTextFieldKeyTyped(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        eliminaButton.setText("Eliminar");
        eliminaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        EAN13TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAN13TextFieldActionPerformed(evt);
            }
        });
        EAN13TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EAN13TextFieldKeyTyped(evt);
            }
        });

        jLabel7.setText("Descrição:");

        jLabel10.setText("Unid.Medida");

        QtdEstoqueTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QtdEstoqueTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(nomeProdutoTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QtdEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EAN13TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(eliminaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DescricaoProdutoTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UnidMedidaProdutoTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ValorProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAN13TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(QtdEstoqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DescricaoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UnidMedidaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(eliminaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValorProdutoTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ValorProdutoTextFieldKeyTyped
    {//GEN-HEADEREND:event_ValorProdutoTextFieldKeyTyped
        // permitir que somente números sejam digitados no campo VALOR
 char c = evt.getKeyChar();
 if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) ||
 (c == KeyEvent.VK_DELETE)))
 {
 evt.consume();
 }

    }//GEN-LAST:event_ValorProdutoTextFieldKeyTyped

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
 operacao = OPERACAO_CANCELAR;
 setVisible(false);
 dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
      // valida dados
 if(estaInserindo)
 {
 try
 {
 pCurrent2.setNomeProduto(nomeProdutoTextField.getText());
 }
 catch(IllegalArgumentException ex)
 {
 String msg = "Nome não pode ser vazio";
 JOptionPane.showMessageDialog(this, msg,
 "Dados dos Produtos",
 JOptionPane.ERROR_MESSAGE);
 nomeProdutoTextField.requestFocus();
 return;
 }
 }
 try
 {
 pCurrent2.setPrecoProduto(ValorProdutoTextField.getText());
 }
 catch(IllegalArgumentException ex)
 {
 String msg = "VALOR Inválido.\n" +
 "Formatos Válidos:\n" +
 " S" +
 " ";
 JOptionPane.showMessageDialog(this, msg,
 "Dados dos Produtos",
 JOptionPane.ERROR_MESSAGE);
 ValorProdutoTextField.requestFocus();
 return;
 }

 // verifica se nome já foi inserido
 if(estaInserindo)
 {
 ArrayList<Produto> produtos =
janelaPai2.buscaNomesTelefones(nomeProdutoTextField.getText());
 if((produtos != null) && (produtos.size() > 0))
 {
 JOptionPane.showMessageDialog(this, "Produto já cadastrado!",
 "Dados dos Produtos",
 JOptionPane.ERROR_MESSAGE);
 nomeProdutoTextField.requestFocus();
 return;
 }
 }

 // adiciona ou atualiza dados pessoa na base de dados
 if (estaInserindo)
 {

int id = DadosProdutos.inserirProduto(bdConnection, EAN13TextField.getText() , nomeProdutoTextField.getText(),
                                                    DescricaoProdutoTextField.getText() , QtdEstoqueTextField.getText(),
                                                    ValorProdutoTextField.getText() , UnidMedidaProdutoTextField.getText() );



//public static int inserirProduto(Connection bdConnection, String nomeProduto, String EAN13, String descricaoProduto,
//                                                           String precoProduto, String qtdEstoque, String unidMedida


if(id < 0)
 return;
 //atualiza ID do Produto inserida na base de dados;
 pCurrent2.setId(id);
 }
 else
 {
 DadosProdutos.alterarTelefone(bdConnection, pCurrent2);
 }

 // indica que operação de inserção foi feita e fecha janaela
 operacao = OPERACAO_OK;
 setVisible(false);
 dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    
    
    private void eliminaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminaButtonActionPerformed
    {//GEN-HEADEREND:event_eliminaButtonActionPerformed
        
 // elimina pessoa da base de dados
 DadosProdutos.eliminarProduto(bdConnection, pCurrent2);

 // indica que operação de inserção foi feita e fecha janela
 operacao = OPERACAO_ELIMINAR;
 setVisible(false);
 dispose();
    }//GEN-LAST:event_eliminaButtonActionPerformed

    
    private void EAN13TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EAN13TextFieldKeyTyped
                      
        // permitir que somente números sejam digitados no campo Estoque
 char c = evt.getKeyChar();
 if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) ||
 (c == KeyEvent.VK_DELETE)))
 {
 evt.consume();
    }//GEN-LAST:event_EAN13TextFieldKeyTyped
    }
    
    
    private void nomeProdutoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoTextFieldActionPerformed

    private void QtdEstoqueTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtdEstoqueTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_QtdEstoqueTextFieldKeyTyped

    private void EAN13TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAN13TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAN13TextFieldActionPerformed
 
    
    
    
    
    
   //  private void fone_residencialTextFieldKeyTyped(java.awt.event.KeyEvent evt) {                                                 
                      
        // permitir que somente números sejam digitados no campo telefone
  //char c = evt.getKeyChar();
  //if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) ||
  //(c == KeyEvent.VK_DELETE)))
  //{
  //evt.consume();
    // }                                                
 // }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TelaInserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TelaInserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TelaInserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TelaInserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                TelaInserirProduto dialog = new TelaInserirProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescricaoProdutoTextField;
    private javax.swing.JTextField EAN13TextField;
    private javax.swing.JTextField QtdEstoqueTextField;
    private javax.swing.JTextField UnidMedidaProdutoTextField;
    private javax.swing.JTextField ValorProdutoTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton eliminaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeProdutoTextField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
