
package TelaPrincipal;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ProgressBar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import TelaPrincipal.TelaPrincipal;

/**
 *
 * @author Jr
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        
        
                try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        initComponents();
       

        
        this.setSize(615, 412); //limitando o tamanho da minha tela
        this.setLocationRelativeTo(null); //centralizando a tela
        this.setResizable(false); //desabilitar o maximizar
         setIcon();
         
        this.setVisible(false);
        
//        this.setEnabled(false);
    
             
//             this.setExtendedState(MAXIMIZED_BOTH); //abrir a tela no modo maximizado
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextoSenha = new javax.swing.JPasswordField();
        TextoLogin = new javax.swing.JTextField();
        BotaoFechar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ENTRAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 220, 100, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 170, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 130, 80, 30);

        TextoSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(TextoSenha);
        TextoSenha.setBounds(280, 170, 140, 30);

        TextoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TextoLogin);
        TextoLogin.setBounds(280, 130, 140, 30);

        BotaoFechar.setText("FECHAR");
        BotaoFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFechar);
        BotaoFechar.setBounds(500, 10, 90, 23);

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel4.setText("Júnior'S  Soft");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 350, 210, 70);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("2018");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 380, 40, 17);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 153));
        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(170, 270, 270, 17);

        jLabel6.setText(" ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 250, 270, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5231551944.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setPreferredSize(new java.awt.Dimension(612, 405));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 612, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                        
        // verificar se o usuário foi informado
        if(TextoLogin.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Usuário não foi informado!", "Login    ", JOptionPane.ERROR_MESSAGE);
            TextoLogin.requestFocus();
            return;
        }
        
        // verificar se o senha foi informado
        if(TextoSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Senha não foi informado!", "Senha", JOptionPane.ERROR_MESSAGE);
            TextoSenha.requestFocus();
            return;
        }
//------------------------------------------------------------------------------        
              if ( TextoLogin.getText().equals("ALUNO") &&
                   TextoSenha.getText().equals("SENAC")) {
                   
                   
                  JOptionPane.showMessageDialog(null, "Senha Correta");
                
                  
new Thread(){
int varAux = 0;
    public void run(){
        for(int i = 0 ; i < 101 ; i++){
            try{
                sleep(100);
                jProgressBar1.setValue(i);
            } catch(InterruptedException ex){
                Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE);
            }
    
            
            varAux = i;    
        
            if(varAux == 100){
                
                TelaPrincipal form = new TelaPrincipal();
                form.setVisible(true);
                
                TelaLogin form2 = new TelaLogin();
                
                
                //.setDefaultCloseOperation(HIDE_ON_CLOSE); //usar esse código para fechar esse JFRAME e não a tela principal;
                
            }
        
        }
        
    }  
            } .start();
                   jLabel6.setText("Carregando banco de dados ...");
     
                 // dispose();//FECHAR A TELA ANTERIOR
         
            
            
            
        }
                   
                  
              
   /*           
           if(varAux == 100){
                
               public void run(){
                try{
                    Thread.sleep(100);
                }
                catch(Esception e){
                    
                }
               
                NewJFrame form = new NewJFrame();
                form.setVisible(true);
                }
        }
              
   */           
              
                   
                       
                   
              
              else
                  JOptionPane.showMessageDialog(null,"LOGIN OU SENHA INVÁLIDO");
        
        
        
        
   /*     
      tela2 t;
        try {
            t = new tela2(); //instanciando a classe que tem seu JFrame de cadastro
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }*/
//         this.dispose(); //fecha a tela de login
//        t.setVisible(true); //abrindo na tela
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoFecharActionPerformed

    private void TextoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFechar;
    private javax.swing.JTextField TextoLogin;
    private javax.swing.JPasswordField TextoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       
//    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("JRICON.png")));

//ImageIcon icone = new ImageIcon("JRICON.png");
//setIconImage(icone.getImage());

this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/JRICON.png")).getImage()); //Colocando meu icon

    }


}
