package Vendas;
//==============================================================================
import Produtos.DadosProdutos;
import Produtos.Produto;
import static Produtos.TelaInserirProduto.OPERACAO_CANCELAR;
import agendatelefonica.DadosPessoas;
import agendatelefonica.MyPostgreSQL;
import agendatelefonica.Pessoa;
import java.awt.Choice;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import static sun.rmi.registry.RegistryImpl.getID;
//==============================================================================
//==============================================================================
public class VendaDialog extends javax.swing.JDialog {

    private MyPostgreSQL pgBD; // conexão com banco de dados
    private ArrayList<Pessoa> listaPessoas;
    private ArrayList<Produto> listaProdutos;
    private ArrayList<Venda> listaVenda;
    
    
 // operacao feita pelo usuario
 public static final int OPERACAO_OK = 0;
 public static final int OPERACAO_ELIMINAR = 1;
 public static final int OPERACAO_CANCELAR = 2;
 
 private Connection bdConnection;
 private Venda pCurrent2; // dados do produto corrente
 private int operacao;
 private boolean estaInserindo;
 
 
 
 //CRIANDO OBJETOS PARA jogar QTD da tabela produto para tabela venda
    //pegando a linha 0 e coluna 4 e transformando em String;
    private String qtdSuperior; 
    private int qtdINT3 = 0;
    private Object jblFindOF;
    
    private final String PagamentosChoise = "Boleto";

//==============================================================================
//==============================================================================
    public VendaDialog(java.awt.Frame parent, boolean modal) {
       
        super(parent, modal);
        
        initComponents();
        
        
        
        
 pCurrent2 = new Venda();
 estaInserindo = true;        
        
    
 //   getContentPane().setBackground(Color.BLACK); //Colocar a tela com cor
    
 //   jPanel1.setBackground(Color.BLUE); //Colocar o painel com cor

 //getContentPane().setBackground(new Color(100,100,250,250)); //escolher a tonalização da cor
 
//------------------------------------------ 
PagamentosChoice.addItem("Dinheiro");
PagamentosChoice.addItem("Débito");
PagamentosChoice.addItem("Crédito");
PagamentosChoice.addItem("Boleto");



 if( PagamentosChoise.equals("Dinheiro")){
      qtdLabel.setText(String.valueOf("0")); 
 ValorTotalLabel.setText(String.valueOf("0"));
 }
//------------------------------------------


 if( PagamentosChoise.equals("Débito")){
      qtdLabel.setText(String.valueOf("1")); 
 ValorTotalLabel.setText(String.valueOf("1"));
 }
//------------------------------------------ 
 
 
 
 
 // adiciona change listener no campo de texto:
 // o método filtroAlterou() será chamado toda vez que o
 // conteúdo de filtroTextField for alterado.
 filtroTextFieldCliente.getDocument().addDocumentListener(new DocumentListener() {
 @Override
 public void insertUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 @Override
 public void removeUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 @Override
 public void changedUpdate(DocumentEvent e) {
 filtroAlterou();
 }
 });
 
 
  filtroTextFieldProduto.getDocument().addDocumentListener(new DocumentListener() {
 @Override
 public void insertUpdate(DocumentEvent e) {
 filtroProdutosAlterou();
 }
 @Override
 public void removeUpdate(DocumentEvent e) {
 filtroProdutosAlterou();
 }
 @Override
 public void changedUpdate(DocumentEvent e) {
 filtroProdutosAlterou();
 }
 });
 
 
 

 // conecta com base de dados
 pgBD = new MyPostgreSQL();
 pgBD.conecta();

 // recupera dados da base de dados
 listaPessoas = DadosPessoas.lerDados(pgBD.getConnection());
 mostraDados(listaPessoas);

 // recupera dados da base de dados
 listaProdutos = DadosProdutos.lerDados(pgBD.getConnection());
 mostraDadosProdutos(listaProdutos);
 
 
 // centralizar a janela na tela
 this.setLocationRelativeTo(null);
 this.qtdSuperior = (String) produtosTable.getValueAt(0,4); //INICIALIZANDO O OBJETO    qtdSUPERIOR que este é o valor da quantidade de determinado produto
 
    }
//==============================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InserirClienteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pessoasTable = new javax.swing.JTable();
        filtroTextFieldCliente = new javax.swing.JTextField();
        ButtonCLEARfiltroCLIENTE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendaTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PagamentosChoice = new java.awt.Choice();
        qtdLabel = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        filtroTextFieldProduto = new javax.swing.JTextField();
        subButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        ButtonCLEARfiltroPRODUTO = new javax.swing.JButton();
        ClienteLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        inserindoClientejLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel1.setToolTipText("Cliente");

        InserirClienteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InserirClienteButton.setText("Inserir");
        InserirClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirClienteButtonActionPerformed(evt);
            }
        });

        pessoasTable.setAutoCreateRowSorter(true);
        pessoasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pessoasTable.getTableHeader().setReorderingAllowed(false);
        pessoasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pessoasTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pessoasTable);
        if (pessoasTable.getColumnModel().getColumnCount() > 0) {
            pessoasTable.getColumnModel().getColumn(0).setMinWidth(40);
            pessoasTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            pessoasTable.getColumnModel().getColumn(0).setMaxWidth(40);
            pessoasTable.getColumnModel().getColumn(1).setMinWidth(100);
        }

        ButtonCLEARfiltroCLIENTE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ButtonCLEARfiltroCLIENTE.setText("CLEAR");
        ButtonCLEARfiltroCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCLEARfiltroCLIENTEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filtroTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCLEARfiltroCLIENTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InserirClienteButton))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filtroTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonCLEARfiltroCLIENTE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas"));

        vendaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Produto", "Qtd", "Vlr Unit.", "Vlt Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vendaTable);
        if (vendaTable.getColumnModel().getColumnCount() > 0) {
            vendaTable.getColumnModel().getColumn(0).setMinWidth(40);
            vendaTable.getColumnModel().getColumn(0).setMaxWidth(40);
            vendaTable.getColumnModel().getColumn(2).setMinWidth(40);
            vendaTable.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Quantidade:");

        jLabel5.setText("Valor total:");

        jLabel4.setText("Pagamento:");

        PagamentosChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PagamentosChoiceItemStateChanged(evt);
            }
        });

        qtdLabel.setText(" ");

        ValorTotalLabel.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ValorTotalLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtdLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PagamentosChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qtdLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(PagamentosChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ValorTotalLabel)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));
        jPanel2.setToolTipText("Produtos");

        produtosTable.setAutoCreateRowSorter(true);
        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "EAN", "Produto", "Descrição", "Qtd", "Valor", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtosTable.getTableHeader().setReorderingAllowed(false);
        produtosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(produtosTable);
        if (produtosTable.getColumnModel().getColumnCount() > 0) {
            produtosTable.getColumnModel().getColumn(0).setMinWidth(1);
            produtosTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            produtosTable.getColumnModel().getColumn(0).setMaxWidth(1);
            produtosTable.getColumnModel().getColumn(1).setMinWidth(120);
            produtosTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            produtosTable.getColumnModel().getColumn(1).setMaxWidth(120);
            produtosTable.getColumnModel().getColumn(2).setMinWidth(140);
            produtosTable.getColumnModel().getColumn(2).setPreferredWidth(140);
            produtosTable.getColumnModel().getColumn(2).setMaxWidth(140);
            produtosTable.getColumnModel().getColumn(3).setMinWidth(140);
            produtosTable.getColumnModel().getColumn(3).setPreferredWidth(140);
            produtosTable.getColumnModel().getColumn(3).setMaxWidth(140);
            produtosTable.getColumnModel().getColumn(4).setMinWidth(60);
            produtosTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            produtosTable.getColumnModel().getColumn(4).setMaxWidth(60);
            produtosTable.getColumnModel().getColumn(5).setMinWidth(60);
            produtosTable.getColumnModel().getColumn(5).setPreferredWidth(60);
            produtosTable.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        filtroTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTextFieldProdutoActionPerformed(evt);
            }
        });

        subButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subButton.setText("-");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        ButtonCLEARfiltroPRODUTO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ButtonCLEARfiltroPRODUTO.setText("CLEAR");
        ButtonCLEARfiltroPRODUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCLEARfiltroPRODUTOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(filtroTextFieldProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCLEARfiltroPRODUTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCLEARfiltroPRODUTO)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filtroTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subButton)
                        .addComponent(addButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonCLEARfiltroPRODUTO, addButton, subButton});

        ClienteLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClienteLabel.setText("Cliente: ");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Efetuar Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        inserindoClientejLabel.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inserindoClientejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClienteLabel)
                            .addComponent(inserindoClientejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
//==============================================================================    
    private void produtosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosTableMouseClicked
        // double-click: editar dados da pessoa
        
        
        //if(produtosTable.getSelectedRow()){
            
        
        
        int jogarTextFieldLINHAselect =  produtosTable.getSelectedRow();
   //    for (int i = 0 ; i <= produtosTable.getRowCount()-1 ; i++) {
           
       filtroTextFieldProduto.setText(produtosTable.getValueAt(jogarTextFieldLINHAselect, 2).toString());
//}






   
        //  int rowModel2 = produtosTable.getSelectedRow(); // coordenadas do modelo
            // coordenadas da view
        //   int rowView2 = produtosTable.convertRowIndexToModel(rowModel2);
            
        //    filtroTextFieldProduto.setText(String.valueOf(5));
            
  //      if (evt.getClickCount() >= 2)
        {
            
            
            /*
            * IMPORTANTE: quando uma tabela usa um ordenador, os dados que o usuário
            * vê podem estar em uma ordem diferente da que está especificada no modelo
            * interno (data model). Os dados que o usuário vê é conhecido como uma view,
            * e possui seu próprio conjunto de coordenadas. Portanto, é necessário
            * converter as coordenadas do modelo para as coordenadas da view.
            *
            * Quando usar um ordenador, SEMPRE converta as coordenadas das células
            */
          //  int rowModel = produtosTable.getSelectedRow(); // coordenadas do modelo
            // coordenadas da view
          //  int rowView = produtosTable.convertRowIndexToModel(rowModel);

            
            
            // obtem dados do produto selecionada
           // DefaultTableModel model = (DefaultTableModel) produtosTable.getModel();
          //  ArrayList<Produto> lista =  buscaProdutoEAN((String)model.getValueAt(rowView, 2));
         //   if((lista == null) || lista.isEmpty())
          //  return;

        //    Produto selecionado = lista.get(0);

            // ativa janela para editar dados da pessoa selecionada
           // TelaInserirProduto pDialog = new TelaInserirProduto(this, true);
            //pDialog.setConnection(pgBD.getConnection());
            //pDialog.setTitle("Manutenção dados");
            //pDialog.setProduto(selecionado);
            //pDialog.inserindoNovo(false);
            //pDialog.setVisible(true);
            //switch(pDialog.getOperacao())
            //{
             //   case TelaInserirProduto.OPERACAO_OK:
                // obtém dados informados pelo usuário
               // Produto p = listaProdutos.set(WIDTH, selecionado);
         
                
                

                //count += Double.parseDouble(produtosTable.getValueAt(i, 4).toString());
                
//                selecionado.setId(p.getId());

                // atualiza telefone (nome não pode ser alterado)
                //selecionado.setFone(p.getFone());
                // atualiza dados na tabela
                //model.setValueAt(p.getFoneFormatado(), rowView, 1);

                //selecionada.setFone_Comercial(p.getFone_Comercial_Formatado());
                // atualiza dados na tabela
                //selecionado.setFone_Comercial(p.getFone_Comercial());
                // model.setValueAt(p.getFone_Comercial(), rowView, 2);

                //selecionado.setFone_Residencial(p.getFone_Residencial());
                //model.setValueAt(p.getFone_Residencial(), rowView, 3);

                // selecionado.setCPF(p.getCPF());
                // model.setValueAt(p.getCPF(), rowView, 4);

                //selecionado.setRG(p.getRG());
                //model.setValueAt(p.getRG(), rowView, 5);

              //  break;
              //  case TelaInserirProduto.OPERACAO_ELIMINAR:
                // elimina pessoa da lista de pessoas
    ////////////////////////////            listaProdutos.remove(selecionado);

                // atualiza dados na tabela
              //////////  model.removeRow(rowView);
            //    break;
           // }
        }
    }//GEN-LAST:event_produtosTableMouseClicked
//==============================================================================
//==============================================================================
    private void filtroTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTextFieldProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTextFieldProdutoActionPerformed
//==============================================================================
//==============================================================================
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
operacao = OPERACAO_CANCELAR;
 
//colocar aqui o código para limpar o ArrayList de vendas e limpar a gridtable


while(vendaTable.getModel().getRowCount()>0){
    ((DefaultTableModel) vendaTable.getModel()).removeRow(0);

}


 qtdLabel.setText(String.valueOf("")); 
 ValorTotalLabel.setText(String.valueOf(""));

         
    }//GEN-LAST:event_jButton2ActionPerformed
//==============================================================================
//==============================================================================
    private void InserirClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirClienteButtonActionPerformed

 
       inserindoClientejLabel.setText(filtroTextFieldCliente.getText());
     

        
        
    }//GEN-LAST:event_InserirClienteButtonActionPerformed
//==============================================================================
//==============================================================================
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

            
 int jogarTextFieldLINHAselect =  produtosTable.getSelectedRow();
 
int qtdINT = Integer.parseInt(qtdSuperior); // pegando a variável qtd tranformado em INT e
                                            // jogando dentro da variável qtdINT
  
                                                             
                                             
System.out.println(vendaTable.getRowCount());



if(vendaTable.getRowCount() >= 0){
DefaultTableModel model = (DefaultTableModel) vendaTable.getModel(); //criando a primeira linha na tabela de venda
Object[] linha = {0};
model.addRow(linha);
System.out.println(vendaTable.getRowCount());

for (int i = vendaTable.getRowCount() ; i <= i ; i++) {//Inserindo o produto na próxima linha
   
    vendaTable.setValueAt(i, i-1, 0);
    vendaTable.setValueAt(String.valueOf(filtroTextFieldProduto.getText()), i-1, 1);
    
    
    
    
    
    
    
    
    vendaTable.setValueAt(produtosTable.getValueAt(0, 5), i-1, 3);//pegando o valor qtd da linha 0
                                         //e coluna 5 da produtosTable e jogando na vendaTable coluna 3
                                         
    vendaTable.setValueAt(1, i-1, 2);
   // vendaTable.setValueAt((produtosTable.getSelectedRow()), i-1, 2);

}
}

                                                         
   
    int qtdINT2;
        String var = qtdSuperior;
   
        

     produtosTable.setValueAt(qtdINT - 1, 0, 4); // diminuindo a quantidade que sobrou de produtos
                                                 // e jogando na table produtos
 
     
     
     qtdINT3 = qtdINT3 +1;

     if(qtdINT3 <= 6){
     vendaTable.setValueAt(qtdINT3 , 0, 2); // aqui estou inserindo a variável atdINT3 na linha 0
                                            // coluna 2 da vendaTable
                                            
                                            
     }
     
qtdINT2 = qtdINT -1;
                                                         
     
    

int count = 0 ;
int count2 = 0 ;

for (int i = 0 ; i <= vendaTable.getRowCount()-1 ; i++) {
count += Double.parseDouble(vendaTable.getValueAt(i, 4).toString());
count2 += Double.parseDouble(vendaTable.getValueAt(i, 5).toString());
}


 qtdLabel.setText(String.valueOf(count)); 
 ValorTotalLabel.setText(String.valueOf(count2));
                 
 if(qtdINT2 > 0){
 qtdSuperior = String.valueOf(qtdINT2) ;
 
 vendaTable.setValueAt(qtdSuperior , 4, 2);
 }
 
 
    }//GEN-LAST:event_addButtonActionPerformed
//==============================================================================
//==============================================================================
    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
     
     int qtd1;
     int qtd2;
     
     int qtdINT12;
     int qtdINT22;

     
     qtd1 =  (int)vendaTable.getValueAt(0,2); //pegando a linha 0 e coluna 4 e transformando em String
     qtd2 =  (int)produtosTable.getValueAt(0,4);

    qtdINT12 = qtd1 - 1;
    qtdINT22 = qtd2 + 1;


     if(qtd1 > 0){


     produtosTable.setValueAt(qtdINT22 , 0, 4); //dimunindo o valor que sobrou de produtos e jogando na table produtos
  

     vendaTable.setValueAt(qtdINT12 , 0, 2); // aqui estou pegando o valor da linha 0 e coluna 2 da TABELA PRODUTO
                                                             // e jogando na linha 1 coluna 1 da TABELA VENDA
                                                             
//     }
             
         
     }
    }//GEN-LAST:event_subButtonActionPerformed

    private void PagamentosChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PagamentosChoiceItemStateChanged

    }//GEN-LAST:event_PagamentosChoiceItemStateChanged

    private void ButtonCLEARfiltroPRODUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCLEARfiltroPRODUTOActionPerformed
filtroTextFieldProduto.setText("");
    }//GEN-LAST:event_ButtonCLEARfiltroPRODUTOActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ButtonCLEARfiltroCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCLEARfiltroCLIENTEActionPerformed
        filtroTextFieldCliente.setText("");
        inserindoClientejLabel.setText("");
    }//GEN-LAST:event_ButtonCLEARfiltroCLIENTEActionPerformed

    private void pessoasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoasTableMouseClicked
              
        int jogarTextFieldLINHAselect =  pessoasTable.getSelectedRow();
   //    for (int i = 0 ; i <= produtosTable.getRowCount()-1 ; i++) {
           
       filtroTextFieldCliente.setText(pessoasTable.getValueAt(jogarTextFieldLINHAselect, 1).toString());
//}

    }//GEN-LAST:event_pessoasTableMouseClicked
//==============================================================================    
//==============================================================================        
    public ArrayList<Pessoa> buscaNomesTelefones(String procurado)
    {
        if((procurado == null) || procurado.isEmpty())
 return listaPessoas;

 ArrayList<Pessoa> pessoasEncontradas = new ArrayList<>();
 String minusculo = procurado.toLowerCase();
 boolean achou = false;

 // percorrer toda a lista de pessoas
 for(Pessoa p : listaPessoas)
 {
 // verifica se dado procurado aparece no nome ou telefone
 if(p.getNome().toLowerCase().contains(minusculo) ||
 p.getFone().contains(procurado)//||
 //p.getFone_Comercial().contains(procurado)
         )
 {
 achou = true;
 pessoasEncontradas.add(p);
 }
 }

 if(achou)
 return pessoasEncontradas;
 else
 return null;
    }
    
    
//==============================================================================
      private void filtroAlterou()
    {
  ArrayList<Pessoa> filtro = buscaNomesTelefones(filtroTextFieldCliente.getText());
 mostraDados(filtro);

    }
    
//==============================================================================    
    private void mostraDados(ArrayList<Pessoa> dados)
    {
       try
 {
 // limpa dados da tabela
 DefaultTableModel model = (DefaultTableModel) pessoasTable.getModel();
 model.setRowCount(0);
 
 

 if((dados == null) || (dados.isEmpty()))
 return;

 // percorrer lista de pessoas e mostrar dados
 for (Pessoa p : dados)
 {                                                                          //=-=-=-=-=-=-=-=-=-//=-=-=-=-=-=-=-=-=-
 model.addRow(new Object[]{p.getId(), p.getNome()});
// model.addTableModelListener(new Object[]{p.getNome()});
// add os 3 campos em pessoa , que é add na lista, que depois joga na tabela da tela gráfica
                                                                        
 }
 }
 catch(Exception ex)
 {
 JOptionPane.showMessageDialog(this,
"Erro ao atualizar tabela\n" + ex.getMessage(),
 "Mostrar dados", JOptionPane.ERROR_MESSAGE);
 }

    }
//==============================================================================    
   
    
    // leitura do arquivo contendo dados da agenda
 public static ArrayList<Pessoa> lerDados(Connection bdConnection)
 {
 ArrayList<Pessoa> pessoas = new ArrayList<>();
 if (bdConnection == null)
 return pessoas;

 try
 {
 String sql_str = "SELECT * FROM pessoas ORDER BY nome";
 PreparedStatement stmt = bdConnection.prepareStatement(sql_str);
 ResultSet rs = stmt.executeQuery();
 int id;
 String nome, fone, fone_comercial, fone_residencial, CPF, RG, Endereco,  Complemento, Setor, Cidade, UF, Cep;
 Pessoa novaPessoa;

 // percorre conjunto de pessoas retornadas pelo banco de dados
 while (rs.next())
 {
 // obtém dados da pessoa corrente
 id = rs.getInt("id");
 nome = rs.getString("nome");
 fone = rs.getString("fone");
 fone_comercial = rs.getString("fone_comercial");
 fone_residencial = rs.getString("fone_residencial");
 CPF = rs.getString("CPF");
 RG = rs.getString("RG");
 Endereco = rs.getString("Endereco");
 Complemento = rs.getString("Complemento"); 
 Setor = rs.getString("Setor");
 Cidade = rs.getString("Cidade"); 
 UF = rs.getString("UF");
 Cep = rs.getString("Cep");
     
    
    
 
// cria nova pessoa e a adiciona na lista
 novaPessoa = new Pessoa(id, nome, fone, fone_comercial, fone_residencial, CPF, RG, Endereco,  Complemento, Setor, Cidade, UF, Cep );
 pessoas.add(novaPessoa);
 }

 stmt.close();
 rs.close();

 // retorna lista de pessoas
 return pessoas;
 } catch(SQLException ex) {
 JOptionPane.showMessageDialog(null,
 "Erro na consulta SQL\n" + ex.getMessage(),
 "Ler Dados", JOptionPane.ERROR_MESSAGE);
 return pessoas;
 }}
//============================================================================== 
 
 
 
 public ArrayList<Produto> buscaProdutoEAN(String procurado)
    {
        if((procurado == null) || procurado.isEmpty())
 return listaProdutos;

 ArrayList<Produto> produtosEncontrados = new ArrayList<>();
 String minusculo = procurado.toLowerCase();
 boolean achou = false;

 // percorrer toda a lista de pessoas
 for(Produto p : listaProdutos)
 {
 // verifica se dado procurado aparece no nome ou telefone
 if(p.getNomeProduto().toLowerCase().contains(minusculo) ||
 p.getEAN13().contains(procurado)//||
 //p.getFone_Comercial().contains(procurado)
         )
 {
 achou = true;
 produtosEncontrados.add(p);
 }
 }

 if(achou)
 return produtosEncontrados;
 else
 return null;
    }
    
    private void filtroProdutosAlterou()
    {
  ArrayList<Produto> filtroProduto = buscaProdutoEAN(filtroTextFieldProduto.getText());
 mostraDadosProdutos(filtroProduto);

    }
    
    
    
    private void mostraDadosProdutos(ArrayList<Produto> dados)
    {
       try
 {
 // limpa dados da tabela
 DefaultTableModel model = (DefaultTableModel) produtosTable.getModel();
 model.setRowCount(0);

 if((dados == null) || (dados.isEmpty()))
 return;

 // percorrer lista de pessoas e mostrar dados
 for (Produto p : dados)
 {                                                                          //=-=-=-=-=-=-=-=-=-//=-=-=-=-=-=-=-=-=-
 model.addRow(new Object[]{p.getId(), p.getEAN13(), p.getNomeProduto(),  p.getDescricaoProduto(), 
                           p.getQtdEstoque(), p.getPrecoProduto(),  p.getUnidMedida()});
            
// add os 3 campos em pessoa , que é add na lista, que depois joga na tabela da tela gráfica
                                                                        
 }
 }
 catch(Exception ex)
 {
 JOptionPane.showMessageDialog(this,
"Erro ao atualizar tabela\n" + ex.getMessage(),
 "Mostrar dados", JOptionPane.ERROR_MESSAGE);
 }

    }
 
//==============================================================================

 
 
   
    private void mostraDadosdaVenda(ArrayList<Venda> dados2)
    {
       try
 {
 // limpa dados da tabela
 DefaultTableModel model = (DefaultTableModel) vendaTable.getModel();
 model.setRowCount(0);

 if((dados2 == null) || (dados2.isEmpty()))
 return;

 // percorrer lista de venda e mostrar dados
 for (Venda p : dados2)
 {                                                                          //=-=-=-=-=-=-=-=-=-//=-=-=-=-=-=-=-=-=-
 model.addRow(new Object[]{p.getId(), p.getNomeProduto(), p.getNF()});
            
// add os 3 campos em pessoa , que é add na lista, que depois joga na tabela da tela gráfica
                                                                        
 }
 }
 catch(Exception ex)
 {
 JOptionPane.showMessageDialog(this,
"Erro ao atualizar tabela\n" + ex.getMessage(),
 "Mostrar dados", JOptionPane.ERROR_MESSAGE);
 }

    }
 
    
    
    
    
    
    
    
    //==============================================================================    
   
    
    // leitura do arquivo contendo dados da agenda
 public static ArrayList<Venda> lerDados2(Connection bdConnection)
 {
 ArrayList<Venda> vendas = new ArrayList<>();
 if (bdConnection == null)
 return vendas;

 try
 {
 String sql_str = "SELECT * FROM vendas ORDER BY nomeProduto";
 PreparedStatement stmt = bdConnection.prepareStatement(sql_str);
 ResultSet rs = stmt.executeQuery();
 int id;
 String nomeProduto , nf/*, fone_comercial, fone_residencial, CPF, RG, Endereco,  Complemento, Setor, Cidade, UF, Cep*/;
 Venda novaVenda;

 // percorre conjunto de pessoas retornadas pelo banco de dados
 while (rs.next())
 {
 // obtém dados da pessoa corrente
 id = rs.getInt("id");
 nomeProduto = rs.getString("nomeProduto");
 nf = rs.getString("nf");;
 /*
 fone_comercial = rs.getString("fone_comercial");
 fone_residencial = rs.getString("fone_residencial");
 CPF = rs.getString("CPF");
 RG = rs.getString("RG");
 Endereco = rs.getString("Endereco");
 Complemento = rs.getString("Complemento"); 
 Setor = rs.getString("Setor");
 Cidade = rs.getString("Cidade"); 
 UF = rs.getString("UF");
 Cep = rs.getString("Cep");
  */   
    
    
 
// cria nova venda e a adiciona na lista
 novaVenda = new Venda(id, nomeProduto , nf );
 vendas.add(novaVenda);
 }

 stmt.close();
 rs.close();

 // retorna lista de pessoas
 return vendas;
 } catch(SQLException ex) {
 JOptionPane.showMessageDialog(null,
 "Erro na consulta SQL\n" + ex.getMessage(),
 "Ler Dados", JOptionPane.ERROR_MESSAGE);
 return vendas;
 }}
//============================================================================== 
 

 
//==============================================================================
//==============================================================================    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaDialog dialog = new VendaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
//==============================================================================
//==============================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCLEARfiltroCLIENTE;
    private javax.swing.JButton ButtonCLEARfiltroPRODUTO;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JButton InserirClienteButton;
    private java.awt.Choice PagamentosChoice;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField filtroTextFieldCliente;
    private javax.swing.JTextField filtroTextFieldProduto;
    private javax.swing.JLabel inserindoClientejLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable pessoasTable;
    private javax.swing.JTable produtosTable;
    private javax.swing.JLabel qtdLabel;
    private javax.swing.JButton subButton;
    private javax.swing.JTable vendaTable;
    // End of variables declaration//GEN-END:variables


    

    
    
    
    
    
}

